### ISSUE TITLE
NHit monitor should have drop down for selecting different types of triggers

### ISSUE THREAD

**Issue by marzece** [snoplus/minard#19]

**Comment by tlatorre-uchicago** [comment]
Unfortunately this isn't possible with the way the data is currently stored.

**Comment by mnirkko** [comment]
How come there is a drop-down box for the timing, but not for the triggers? Could this be solved using a drop-down containing links to the different trigger types?

**Comment by tlatorre-uchicago** [comment]
The page @marzece is referring to is the Nhit tab. Which one are you talking about?

**Comment by mnirkko** [comment]
It would be nice to be able to switch more quickly between baselines, e.g. for the hourly shift report.

**Comment by marzece** [comment]
I agree, however if you want to switch between the baselines easily you can change the URL fairly easily. For example if you had a url like the following
`http://snopl.us/monitoring/graph?name=100L-Baseline&start=........`
you could change it too
`http://snopl.us/monitoring/graph?name=20-Baseline&start=........`
and that'd let you swap between them somewhat efficiently.
I realize that's not a great solution but it might make waiting for someone to get around to this somewhat more bearable.

That trick works for nearly every graph on minard as well.

**Comment by tlatorre-uchicago** [comment]
Added in https://github.com/snoplus/minard/commit/42533e0694f1e89c97d8c9aa920080c62ddacdac.
