### ISSUE TITLE
timelines x and y axis should be re-scaleable.

### ISSUE THREAD

**Issue by marzece** [snoplus/minard#20]

**Comment by tlatorre-uchicago** [comment]
Can you elaborate on when this would be handy? The way the data is stored makes this not as useful as it might seem since the data is stored for only a certain period of time at a given resolution you can't really "zoom in" on longer time scales because the resolution is limited.

**Comment by marzece** [comment]
Basically this is for when a giant trigger rater burst (or something like that) turns the sparkline plots into delta functions. It'd be nice to be able to zoom in on either axis so that you can ignore the giant spike and get good reasonable resolution on the rest of the plot.

**Comment by tlatorre-uchicago** [comment]
It's now possible to zoom in on the x axis which should address this issue.
