### ISSUE TITLE
pmt noise rate should be plotted versus time

### ISSUE THREAD

**Issue by tlatorre-uchicago** [snoplus/minard#208]
Currently it's very difficult to get an overall feel for the PMT noise rate since the plot is displayed versus run number.

<img width="2160" alt="Screen Shot 2019-03-15 at 1 05 22 PM" src="https://user-images.githubusercontent.com/5834059/54448835-05e79000-4723-11e9-9d43-722b024cca3b.png">

This could be solved by plotting versus time instead of run number.

It might also be cool to display a native graph on the page instead of a ROOT plot so you can select different time ranges, etc.

@edcallaghan

**Comment by edcallaghan** [comment]
I'd implemented the groundwork for improving this a while back but it fell off my radar. See PR #209.
