### ISSUE TITLE
Sparkline graph doesn't show time

### ISSUE THREAD

**Issue by DanPrax** [snoplus/minard#23]
Currently, the sparkline graph for running the Snoplus detector shows the date in the top right corner when hovering the mouse over the graph according to its point on the x-axis, but it doesn't show the time. It would be very useful if it did, as we could tell the exact time events happened instead of approximating, and would make things easier to analyse.

**Comment by fbdescamps** [comment]
I concur that this would be nice to have.

**Comment by tlatorre-uchicago** [comment]
Fixed.
