### ISSUE TITLE
CAEN channel offsets not interpreted correctly

### ISSUE THREAD

**Issue by marzece** [snoplus/minard#24]
![screen shot 2016-12-15 at 9 56 25 pm](https://cloud.githubusercontent.com/assets/4153907/21250185/5f972c52-c311-11e6-8e7b-de86ff8de657.png)

Despite the data saying channel 2 has a different offset the display does not show any difference. Also most of the values should read 0. They instead read -1V.

**Comment by tlatorre-uchicago** [comment]
Fixed in https://github.com/snoplus/minard/commit/bd96050c3f81ae8315cf135f2f4d25878bbf12eb.
