### ISSUE TITLE
periodic shuffling of events between bins

### ISSUE THREAD

**Issue by klabe** [snoplus/minard#29]
As was seen yesterday, the stream page seems to sometimes blink and then shove the missed events into the next time window.  Produces nonphysical spikes in the time series.  This appears to be happening with a regular periodicity of 3.5 minutes currently - perhaps that suggests where to look for the problem.  See attached image.
![periodic_bunching](https://cloud.githubusercontent.com/assets/4554682/22400382/07e184ac-e581-11e6-84f9-1b035c01f76c.png)

**Comment by tlatorre-uchicago** [comment]
This has been determined to be a problem with the builder or dispatcher and not related to minard.
