### ISSUE TITLE
See all baselines

### ISSUE THREAD

**Issue by tannerbk** [snoplus/minard#30]
Would be handy to be able to view of all the baselines simultaneously.

**Comment by mnirkko** [comment]
Is this what you meant?
http://snopl.us/monitoring/snostream?step=3&height=20

**Comment by tlatorre-uchicago** [comment]
I think he means on the sparkline page which you can access by clicking any of those streams.

**Comment by tannerbk** [comment]
Yah, just to be clear, it would be handy to have  a version of this page: 
http://snopl.us/monitoring/graph?name=100L-Baseline&start=2017-02-22T13%3A33%3A21.000Z&stop=2017-02-22T14%3A31%3A51.000Z&step=3
showing all the baselines simultaneously (without the histograms) to easily see correlations between the baselines during baseline shifts.

**Comment by tlatorre-uchicago** [comment]
Added in https://github.com/snoplus/minard/commit/936ba3fd86806c1ff7820a30996cbad7552eb2f6.
