### ISSUE TITLE
Pop-up box with incorrect info on detector state page

### ISSUE THREAD

**Issue by drjeannewilson** [snoplus/minard#59]
On http://snopl.us/monitoring/state/ I get a box when the mouse hovers over the thresholds saying they are not masked in, when they are enabled (and orca says they are masked in)

![screen shot 2017-05-08 at 09 14 02](https://cloud.githubusercontent.com/assets/1036011/25808485/3923d2c2-33d8-11e7-995c-af2b94dcf76b.png)

**Comment by tlatorre-uchicago** [comment]
Fixed in #60.
